version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: fooddelivery_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fooddb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
